spring:
  application:
    name:  @pom.config.server.name@
  profiles:
    active: @pom.profile.name@
  cloud:
    config:
      server:
        git:
          uri: https://github.com/weizd21/oldwei.git #GitHub上面的git仓库名字
          label: develop # 分支
          search-paths: oldwei-config-file # 搜索的目录
          username:
          password:
server:
  port: @pom.config.server.port@


eureka:
  client:
    service-url:
      defaultZone: @pom.register.eureka.server.defaultZone@


#关闭安全认证
management:
  security:
    enabled: false
  #refresh接入点显式暴露出来
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
