
spring:
  application:
    name:  @pom.config.server.name@
  cloud:
    config:
      server:
        git:
          uri: https://github.com/weizd21/oldwei.git #GitHub上面的git仓库名字
          label: develop
          search-paths: oldwei-config-file
#          username: weizd21
#          password: xxxxxxx

server:
  port: @pom.config.server.port@


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
