spring:
  application:
    name: @pom.register.eureka.server.name@ #指定服务名称
  profiles:
    active: @pom.profile.name@

server:
  port: @pom.register.eureka.server.port@ #指定运行端口


eureka:
  instance:
    hostname: localhost #指定主机地址
  client:
    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: false #指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
      defaultZone: http://localhost:8001/eureka
  server:
    enable-self-preservation: false #关闭保护模式

management:
  endpoints:
    enabled-by-default: false
