apiVersion: v1
kind: Config
clusters:
  - cluster:
      api-version: v1
      server: "https://152.136.218.90:6443"
    name: "local"
contexts:
  - context:
      cluster: "local"
      user: "kube-admin-local"
    name: "local"
current-context: "local"
users:
  - name: "kube-admin-local"
    user:
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjlRRDdEZG1TSExhR05uU0tJaXBnUHNId01CMFhQREtFSm9tdGRTbnZqYkkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbnRlc3QtdG9rZW4tNnJrbTQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYWRtaW50ZXN0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNzEwZWU1MWItOTc2Ni00ZTY5LTkyYzgtZTRkMDgzNmUwZmJiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmFkbWludGVzdCJ9.CUQSK95L_ElvELveFD3Y9hEvtsXPGOZ4VsWd81xTb-OQ_jxarKjFitZPoMBryoj8avxvbRTA4RIeOaOzL_LdQQVZ6fJNY3YK1aDFbVKc4NvBIJFz6UIhio77PPs3a0pAdkTLwKaxtloJtUmc5JbB-LVkXbIvY-4Ua0YqFO3dewLhTKcES71y9gI_ABQy7IQPwxkgTGlWb2xOvW1FV8V1yIxegeUeYXfqSiBOzflxgd5YFYSHpmmkxiXLzfjS6ghc5-m_CPQuwGovu-z45TLkgvX37Bf_ZopX5F10PzbVF-h_k6DmQGIhTWdL-W0qE9FmZWKg59bFsz3SHWOJlIshqg
